platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

target 'CloudFonDemo' do
  pod 'CloudFonMobileSDK', :git => 'https://github.com/wilson-wang0311/cloudfon-mobile-sdk.git', :tag => '1.0.1'
  pod 'SnapKit', '~> 5.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
